sonar.projectKey=VerhovnikTeodor_TaskMaster2
sonar.organization=verhovnikteodor

sonar.sources=backend,frontend/src
sonar.tests=backend/__tests__,frontend/src/__tests__

sonar.exclusions=**/node_modules/**,**/coverage/**,**/build/**,**/dist/**,**/*.test.js,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.language=js,ts

sonar.projectName=TaskMaster2
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
